// Mandarin screen text. Formulas and source titles retain their original notation.
window.FILM_ZH = {
 'Written and illustrated by Hunter Bown. Transformatics is his proposed way of organizing these ideas.':'文字与插图：Hunter Bown。Transformatics 是他提出的、组织这些想法的一种方式。',
 'Sources: OpenAI, “Finite time blowup for Navier–Stokes” (2026); openai/math family 376 (6 Oct 2026).':'来源：OpenAI《Finite time blowup for Navier–Stokes》（2026）；openai/math 第 376 族（2026 年 10 月 6 日）。',
 'Narration: Microsoft synthetic voices.':'旁白：微软合成语音。',
 'A complete machine state':'机器的完整状态',
 'stored symbols + next instruction':'存储的符号 + 下一条指令',
 'particle position (x, y, z)':'粒子位置 (x, y, z)',
 'The digits of the coordinates record the symbols.':'坐标的数字记录存储的符号。',
 'Encoding: schematic':'编码示意图',
 'The marked box represents halting. Intermediate motion is arranged to avoid accidental entry.':'标记的盒子表示停机。中间的运动经过安排，避免粒子意外进入。',
 'Machine rules and input':'机器规则与输入',
 'Prescribed force':'规定的外力',
 'The flow stays smooth for all time.':'流动始终保持光滑。',
 'The particle follows the encoded computation.':'粒子按照编码后的计算步骤运动。',
 'Two uses of a prescribed force':'规定外力的两种作用',
 'A smooth force; unbounded peak speed in finite time':'外力光滑；峰值速度在有限时间内变得无界',
 'A smooth flow; particle motion follows a program':'流动光滑；粒子运动遵循程序步骤',
 'General smooth initial data in 3D, no force: still open':'三维空间、一般光滑初始条件、无外力：仍未解决',
 'low and wide':'低而宽','tall and narrow':'高而窄',
 'wave amplitude A(t) / A₀':'波的振幅 A(t) / A₀',
 'halting run: enters':'停机：进入','non-halting run: never enters':'不停机：始终不进入',
 'Motion':'运动','Measurement':'测量','Acceleration':'加速度','Summaries':'状态的概括','The question':'判定条件','Standing':'目前的情况',
 'What the equation measures, what was just proved, and what is still open':'方程描述什么，哪些结果已有证明，哪些问题仍未解决',
 'A TRANSFORMATICS TEACHING FILM':'Transformatics 教学影片',
 'leaves on the right, re-enters on the left':'从右侧离开，从左侧重新进入',
 'A flow moves every particle at once':'流动描述所有粒子的运动',
 'Periodic box: opposite sides are the same place.':'周期盒子：相对的边界彼此连接。',
 'Colour records each particle’s starting position.':'颜色记录每个粒子的初始位置。',
 'velocity field u, particle position X':'速度场 u，粒子位置 X',
 'the flow map is the transformation':'流映射就是这里的变换',
 'Dashed circles: dye at t = 0.  Filled: the same dye now.':'虚线：初始染料区域。色块：同一染料的当前位置。',
 'EXACT SOLUTION · TAYLOR–GREEN CELLS':'精确解 · Taylor–Green 涡胞',
 'velocity the particle records':'粒子运动中的速度',
 '∂ₜu, drawn to scale':'∂ₜu，按实际比例绘制',
 'one cell of the box, enlarged':'放大的一个涡胞',
 'Its velocity keeps turning:':'速度方向不断改变：','the particle accelerates.':'粒子有加速度。',
 'Meanwhile the field’s':'与此同时，速度场的','pattern only fades:':'形状不变，振幅衰减：',
 'chain rule along X(t)':'沿 X(t) 使用链式法则',
 '∂ₜu   change at one fixed point':'∂ₜu   固定位置的变化',
 '(u·∇)u   moving to where velocity differs: advection':'(u·∇)u   移向速度不同的位置：对流',
 'dashed   their sum, the acceleration':'虚线   两项之和，即加速度',
 'LIVE CHECK':'即时计算','high p':'高压强','low p':'低压强',
 'What causes the acceleration?':'加速度由什么产生？',
 'Pressure: high where streams meet between cells,':'压强：涡胞间流动相遇处较高，','low at the cell centres.':'涡胞中心较低。',
 'the pressure force bends the path around the cell':'压强力使粒子沿涡胞转弯',
 'LIVE CHECK AT THE PARTICLE':'粒子位置处的即时计算',
 'same speed all along its layer':'同一流层各处速度相同','Sliding layers':'水平流层',
 'advection vanishes; no pressure is needed':'对流项为零，无需压强变化',
 'N = 2:  exp(−4νt),  four times the rate':'N = 2：exp(−4νt)，衰减速率为四倍',
 'Keep one number':'只保留一个数',
 'Equal energy at t = 0; unequal energy later.':'初始能量相同，以后的能量不同。',
 'Dissipation depends on the gradient; E alone does not record it.':'耗散取决于梯度；仅有 E 没有记录这一信息。',
 'velocity u₁ across the layers':'各流层的速度 u₁','A grid of eight values':'八个网格值',
 'The eight values cannot':'这八个数无法','distinguish the two waves.':'区分两个不同的波。',
 'state':'状态','summary':'概括',
 'the factor criterion: States, models, and exact transfer, §3':'因子判据：《状态、模型与精确传递》第 3 节',
 'Energy E':'能量 E','Eight grid values':'八个网格值',
 'Energy and wavenumber (E, N)':'能量与波数 (E, N)','Eight grid values, N ≤ 3 only':'八个网格值，仅限 N ≤ 3',
 'N = 1 and N = 2 share E(0), not E(t)':'N = 1 与 N = 2 的 E(0) 相同，E(t) 不同',
 'N = 1 and N = 7 share samples, not futures':'N = 1 与 N = 7 的采样值相同，演化不同',
 'E(t) = E(0) exp(−2νN²t) for sliding layers':'流层解满足 E(t) = E(0) exp(−2νN²t)',
 'the samples determine a and N':'采样值可确定 a 与 N','FAILS':'不成立','PASSES':'成立',
 'Next: two results, read with this test in mind.':'接下来，用这个条件理解两个新结果。',
 'Finite change, continuous evolution, and the passage between mathematical models':'有限变化、连续演化，以及数学模型之间的转换',
 'What is Transformatics?':'什么是 Transformatics？',
 'A way of thinking I put together while working on Navier–Stokes with AI tools.':'我在借助 AI 工具研究纳维–斯托克斯问题时，整理的一种思考方式。',
 'STATE':'状态','TRANSFORMATION':'变换','OBSERVABLE':'观测量',
 'what the system is':'系统当前的状态','how it is updated':'状态如何更新','what we measure':'测量什么',
 'act on the measurement, not only the state':'观察更新如何影响测量值',
 'the measurement x²':'测量值 x²',
 'Same square at the start, different squares after one step.':'初始平方相同，更新一步后的平方不同。',
 'When a full state is replaced by a summary,':'用较少的信息概括完整状态时，','which conclusions survive?':'还能确定哪些结论？',
 'finite differences':'有限差分','dynamical systems':'动力系统','numerical analysis':'数值分析','PDE estimates':'偏微分方程估计',
 'Standard tools, organized around one question. Not a new theory of fluids.':'围绕这个问题组织已有的数学工具。',
 'Adapted from the project’s opening chapter, “A calculus of transformations”.':'改编自本项目开篇章节《变换的微积分》。',
 'Three questions about the Navier–Stokes equations':'关于纳维–斯托克斯方程的三个问题',
 'Short summaries tend to merge them. They have different hypotheses and different answers.':'它们的假设不同，所得结论也不同。',
 'Forced breakdown':'有外力时的崩溃','Forced computation':'有外力时的计算','Unforced regularity':'无外力时的正则性',
 'A chosen smooth force':'特定的光滑外力','Smooth flow breaks down in finite time':'光滑流动在有限时间内失去光滑性',
 'PROOF RELEASED · SEPT 2026':'证明已发布 · 2026 年 9 月','NEW PAPERS · OCT 2026':'新论文 · 2026 年 10 月',
 'Smooth for all time, and carries out any computation':'始终光滑，并能执行任意计算',
 'No force at all':'没有外力','Do smooth solutions stay smooth forever?':'光滑解是否始终保持光滑？','OPEN':'未解决',
 'QUESTION':'问题','FORCE':'外力','WHAT IS ASKED OR SHOWN':'问题或结论',
 'First: what the equation actually measures.':'先看方程具体描述什么。',
 'wide':'宽峰','narrow':'窄峰','speed across space · illustration':'速度的空间分布 · 示意图',
 'Four times the peak speed, a twentieth of the width:':'峰值速度为四倍，宽度为二十分之一：',
 'radial–axial section of the core · schematic, aspect exaggerated':'核心的径向—轴向截面 · 示意图，长宽比例经过夸大',
 'axis':'轴','fixed scale':'固定比例','zoomed with the core':'随核心放大','in':'流入','out along the axis':'沿轴向流出',
 'Peak speed is not energy':'峰值速度与能量是不同的量',
 'adds speed squared over space':'速度平方在空间上的积分',
 'peak speed':'峰值速度','core energy':'核心能量','time remaining τ':'剩余时间 τ',
 'published exponents, plotted with h = 0.005':'论文中的指数，绘图取 h = 0.005',
 'Energy alone does not rule this out.':'仅凭能量，不能排除这种情况。',
 'Scalings: OpenAI, “Finite time blowup for Navier–Stokes”, §2.1 and §3.5. Core picture: schematic.':'尺度来源：OpenAI《Finite time blowup for Navier–Stokes》第 2.1、3.5 节。核心图像为示意图。',
 'A force can be defined from any flow':'从给定流动定义所需的外力',
 'the leftover of the equation, called the force':'把代入方程后的剩余项定义为外力',
 'smooth in space and time':'对空间和时间都光滑',
 'zero outside a bounded region of space and time':'在时空的某个有界区域之外为零',
 'every derivative bounded, through the blowup time':'直到爆破时刻，各阶导数都保持有界',
 'choose any incompressible u':'任取一个不可压缩速度场 u','compute the leftover':'计算方程的剩余项','call it the force f':'将它定义为外力 f',
 'the equation now holds by definition':'此时方程按定义成立',
 'teaching example · not the paper’s flow':'教学例子 · 并非论文中的流动',
 'a classical vortex, squeezed by hand':'直接规定一个经典涡旋收缩',
 'swirl speed u_θ across radius r (rescaled to its peak)':'旋转速度 u_θ 随半径 r 的变化（按峰值归一化）',
 'a bounded force stays near here':'有界外力保持在这一量级附近',
 'peak leftover force':'剩余外力的峰值',
 'Not allowed: this force blows up with the flow.':'不符合要求：这个外力也随流动发生爆破。',
 'core':'核心','balanced to leading order':'主阶动量平衡','ring':'环带','outer flow':'外部流动',
 'exact heat flow · no leftover':'精确热流 · 无剩余项','top view · schematic':'俯视图 · 示意图',
 'Leftover imbalance lives in the ring at the core’s edge,':'剩余的不平衡集中在核心边缘的环带中，',
 'and still blows up as τ → 0.':'并在 τ → 0 时仍然变得无界。',
 'It has to be cancelled inside the fluid.':'需要由流体内部的运动来抵消。',
 'Layout: OpenAI, §2.2–2.3 and §3.2 (the stress T is supported in an annulus).':'结构来源：OpenAI，第 2.2–2.3、3.2 节（应力 T 的支集位于环带中）。',
 'Lamb–Oseen profile with its width forced to shrink like √τ; pressure balances u_θ²/r, leaving only f_θ.':'令 Lamb–Oseen 涡旋的宽度按 √τ 收缩；压强平衡 u_θ²/r，剩余项仅为 f_θ。',
 'Averages over one wavelength, computed live:':'在一个波长上的平均值，即时计算：',
 'Waves that average to zero can still push':'平均速度为零，动量通量仍可非零',
 'its divergence acts like a force on the background':'它的散度在背景流动方程中起到力的作用',
 'both positive: realizable':'两个系数均为正，可以实现',
 'one exact wave on the shear U = (Sy, 0)':'剪切流 U = (Sy, 0) 上的一个精确波解',
 'shear':'剪切',
 'Exact Navier–Stokes solution, with the pressure the tilting needs:':'纳维–斯托克斯方程的精确解，包括波峰转向所需的压强：',
 'One wave on a shear':'剪切流中的一个波',
 'crests lean against the shear: the wave draws energy, grows':'波峰逆着剪切倾斜：从背景获得能量，振幅增大',
 'crests lean with the shear: energy goes back; viscosity finishes it':'波峰顺着剪切倾斜：能量传回背景，黏性继续耗散',
 'The published pulses grow by rotation on a collapsing core:':'论文中的脉冲在收缩核心的旋转作用下增长：',
 'this Kelvin shearing wave is an analogue, not the construction.':'这个 Kelvin 剪切波只是类比，并非论文的构造。',
 'Pulse behaviour: OpenAI, §2.2 and §3.3 (seeded, amplified by shear, then viscously damped).':'脉冲行为：OpenAI，第 2.2、3.3 节（小扰动经剪切放大，随后由黏性衰减）。',
 'Two-family positive representation of the stress: OpenAI, §3.2, Figure 4, Proposition 7.5.':'应力的两族正系数表示：OpenAI，第 3.2 节、图 4、命题 7.5。',
 'Collapsing core and smooth outer heat flow':'收缩的核心与外部光滑热流',
 'Leftover imbalance written as a stress in the ring':'把剩余的不平衡写成环带中的应力',
 'Two pulse families cancel it, on finer and finer scales':'在越来越细的尺度上，用两族脉冲抵消应力',
 'Correct new errors until the rest vanishes to every order':'修正新误差，直到剩余项的所有阶导数都消失',
 'Cut off in space; extend the force smoothly past t = 1':'在空间上截断；将外力光滑延拓至 t = 1 之后',
 'Energy bounded, because the force is':'由外力有界推出能量有界',
 'A bounded-energy rival must agree, so blows up too':'同初值、同外力的有界能量光滑解必须一致',
 'Steps in the proof':'证明的各个步骤','Lemma 10.4':'引理 10.4','Lemma 10.5':'引理 10.5',
 'THEOREM 1.1 (OPENAI), IN WORDS':'OpenAI 定理 1.1 的文字说明',
 'For every viscosity ν > 0 there is a smooth force, zero outside a bounded region of space and time, and a smooth solution starting from rest on 0 ≤ t < 1, with':'对每个黏性系数 ν > 0，都存在一个光滑外力，在时空的某个有界区域外为零；并存在从静止出发、在 0 ≤ t < 1 上光滑的解，满足',
 'So no smooth bounded-energy solution exists for all time, alternative (C) on ℝ³; on the periodic box, no global smooth solution at all, (D).':'因此在 ℝ³ 上，不存在全时间光滑且能量有界的解，即情形 (C)；在周期盒子上，不存在全局光滑解，即情形 (D)。',
 'Lean formalization: openai/NavierStokesAndEuler':'Lean 形式化：openai/NavierStokesAndEuler',
 'THE FORCE IS NOT ZERO':'外力不为零',
 'With f = 0 and a fluid at rest, this keeps u = 0.':'f = 0 且初始静止时，这个估计保证 u = 0。',
 'The unforced problem is a different question.':'无外力的正则性问题仍需另行解决。',
 'Source: OpenAI, “Finite time blowup for Navier–Stokes” (166 pp.), Theorem 1.1, Corollary 10.6, §3 outline.':'来源：OpenAI《Finite time blowup for Navier–Stokes》（166 页），定理 1.1、推论 10.6、第 3 节纲要。',
 'Smooth for all time, and computing':'始终光滑，并执行计算',
 'No blowup here. The velocity stays smooth forever;':'这里没有爆破，速度场始终光滑；',
 'the force is designed so that the motion carries out a program.':'外力经过设计，使运动能够执行程序。',
 'source box: every tape whose prefix the rule reads':'源盒子：规则所读取的前缀对应的全部纸带',
 'target box':'目标盒子',
 'schematic route; the map on the box is the exact affine instruction':'路径为示意图；盒子上的映射是精确的仿射指令',
 'A tape is the coordinates of one point.':'一条纸带编码为一个点的坐标。',
 'An ordinary program may forget':'普通程序可能丢失输入信息',
 'input A':'输入 A','input B':'输入 B','output':'输出','(output, A)':'（输出，A）','(output, B)':'（输出，B）',
 'A smooth flow cannot merge two particles.':'光滑流动不能合并两个粒子。',
 'Keep the history, and every step is reversible:':'保留历史记录，使每一步都可逆：',
 'History records: Bennett (1973). Affine symbol updates: Moore (1990–91).':'历史记录：Bennett（1973）。仿射符号更新：Moore（1990–91）。',
 'compute':'计算','flow':'流动','encode':'编码',
 'Encode, then flow, equals compute, then encode: the factor criterion, built in on purpose.':'先编码再流动，等于先计算再编码。构造保证这一关系成立。',
 'Asserted for the material flow at instruction times, on each rule’s whole domain.':'这项关系适用于指令时刻的物质流，以及每条规则的整个定义域。',
 'halts: enters':'停机：进入','never halts: never enters':'不停机：始终不进入',
 'schematic paths · the proof guards every intermediate time':'路径示意图 · 证明控制了所有中间时刻',
 'particle starting at a* = (4, 0, 0); balanced three-stack construction':'初始位置 a* = (4, 0, 0) 的粒子；平衡三栈构造',
 'The force is the leftover of the designed motion, computed from the rule table and input, without running the machine.':'外力是设计的运动代入方程后的剩余项，由规则表和输入计算得到，无需先运行机器。',
 'CONSEQUENCE':'推论',
 'No algorithm decides, for every force in this family, whether the particle will ever arrive. Halting reduces to it.':'不存在一个算法，能够对这一族的每个外力，判定粒子最终是否到达。停机问题可归约到这个问题。',
 'It is not a blowup result.':'这不是爆破结果。','These flows are smooth for all time.':'这些流动始终保持光滑。',
 'The computation is carried by the force.':'计算由外力实现。',
 'Earlier: universal Euler and Beltrami flows; unforced Navier–Stokes universality on adapted metrics, or for tape-bounded machines on a flat torus (Cardona, Miranda, Peralta-Salas, Presas, and others).':'此前已有通用 Euler 流和 Beltrami 流的研究；也有在特制度量下、或平坦环面上的有限纸带机器中，无外力纳维–斯托克斯流的通用计算结果（Cardona、Miranda、Peralta-Salas、Presas 等）。',
 'Source: openai/math (6 Oct 2026), family 376, nine manuscripts; balanced three-stack theorem in “Incompressible Box Transport and Finite Computation”.':'来源：openai/math（2026 年 10 月 6 日）第 376 族；《Incompressible Box Transport and Finite Computation》中的平衡三栈定理。',
 'Where things stand':'目前的情况',
 'Notes and calculations behind this film:':'本片的笔记和计算依据：',
};
// Only these labels contain numerical values generated during rendering.
window.FILM_ZH_DYNAMIC = [
 [/^start ([+−]2)$/, '起点 $1'],
 [/amplitude exp/, '振幅 exp'],
 [/^velocity change measured along the path\s*/, '沿路径测得的速度变化   '],
 [/ from the formula\s*/, ' 由公式计算   '],
 [/^difference /, '差值 '], [/\(finite-difference error\)/, '（有限差分误差）'],
 [/^viscosity accounts for the slow fade \(size here (.*)\)$/, '黏性对应缓慢衰减（此处大小为 $1）'],
 [/acceleration/, '加速度'], [/\(rounding\)/, '（舍入误差）'],
 [/^same amplitude /, '相同振幅 '],
 [/^∫u² is (.*) times that of the wide bump \(computed\).$/, '∫u² 为宽峰的 $1 倍（计算值）。'],
 [/^peak speed  /, '峰值速度  '], [/^core energy /, '核心能量 '],
 [/    force ×/, '    外力 ×'], [/^volume ratio = /, '体积比 = '], [/^sides /, '各边长度 '],
];
window.FILM_ZH_MATH = {
 'acceleration':'加速度','pressure':'压强','viscosity':'黏性',' for both':' 两者相同',
 ' at every ':' 对每个 ','core':'核心','volume':'体积','speed':'速度','the machine halts':'机器停机',
};
